#!/bin/bash
Font_Black="\033[30m"
Font_Red="\033[31m"
Font_Green="\033[32m"
Font_Yellow="\033[33m"
Font_Blue="\033[34m"
Font_Purple="\033[35m"
Font_SkyBlue="\033[36m"
Font_White="\033[37m"
Font_Suffix="\033[0m"  
  
echo -e ""
echo -e "${Font_SkyBlue}【TikTok相关】${Font_Suffix}"
echo -e "================================================"
echo -e "${Font_Green}Residential IP TikTok解锁${Font_Suffix}"
echo ""
echo -e "${Font_Green}✅ ${Font_Suffix} ${Font_SkyBlue}各国家宽IP${Font_Suffix}"
echo -e "${Font_Green}✅ ${Font_Suffix} ${Font_SkyBlue}一键配置${Font_Suffix}"
echo -e "${Font_Green}✅ ${Font_Suffix} ${Font_SkyBlue}支持定制${Font_Suffix}"
echo ""
echo -e "${Font_Yellow}咨询请使用私聊机器人: https://t.me/chabao_bot${Font_Suffix}"
echo -e "================================================"
echo -e ""
echo -e ""
echo -e ""
echo -e ""
